---

- name: install k3s service file
  template:
    src: "k3s.service-master.j2"
    dest: "/etc/systemd/system/k3s.service"
    owner: root
    group: root
    mode: 0755

- name: enable k3s daemon
  systemd:
    name: k3s
    daemon_reload: yes
    state: restarted
    enabled: yes


- name: wait for node token
  wait_for:
    path: /var/lib/rancher/k3s/server/node-token


- name: Read node-token from master
  slurp:
    src: /var/lib/rancher/k3s/server/node-token
  register: node_token


- name: make node token available
  set_fact:
   token: "{{ node_token.content | b64decode | regex_replace('\n', '') }}"


- name: Read kube config
  slurp:
    src: /etc/rancher/k3s/k3s.yaml
  register: kube_config


- name: make config available
  set_fact:
   kube_config: "{{ kube_config }}"
